### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by vedmalex** [Alex-Werner/TyrDB#8]
### Expected Behavior

try to run example folder samples fs-usage to see how it is works

### Current Behavior

failed to run

### Context

i'm using 
node -v 
v15.2.1

### Steps to Reproduce & logs

/Users/vedanta-krit/Work/TyrDB/src/adapters/FsAdapter/methods/findCollection.js:11
    const exists = await this.queue.add('File.exists', path).getResults();
                                                             ^

TypeError: this.queue.add(...).getResults is not a function
    at FsAdapter.findCollection (/Users/vedanta-krit/Work/TyrDB/src/adapters/FsAdapter/methods/findCollection.js:11:62)

**Comment by Alex-Werner** [comment]
Hi @vedmalex, 
Thank you for reporting this issue. 

I think this is due to `Job` returning .execution() instead of `getResults()`. 

I will release an hot fix it in the next hours.
